level_five/basic_app/urls.py
from django.urls import path,include
from basic_app import views

#Templat urls!

app_name = 'basic_app'

urlpatterns = [
	path('register/',views.register,name="registeration"),
	path('user_login/',views.user_login,name="user_login"),
]

level_five/level_five/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
	path('',views.index,name="index"),
    path('admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls')),
    path('logout/',views.user_logout,name='logout'),
    path('special/',views.special,name='special'),
]

level_five/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class userprofileinfo(models.Model):
	user = models.OneToOneField(User,on_delete=models.CASCADE) #extending our user 

	#additional
	portfolio_site = models.URLField(blank=True)

	profile_pic = models.ImageField(upload_to='profile_pics',blank=True)


	def __Str__(self):

		return self.user.username

level_five/basic_app/forms.py
from django import forms
from django.forms import ModelForm

from django.contrib.auth.models import User

from basic_app.models import userprofileinfo

class UserForm(ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta(ModelForm):
		model = User
		fields = ("username","email","password")
			
class userprofileinfoForm(ModelForm):
	class Meta():
		model =  userprofileinfo
		fields = ("portfolio_site","profile_pic")

level_five/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,userprofileinfoForm


#
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required



# Create your views here.
def index(request):
	return render(request,'basic_app/index.html')

@login_required
def special(request):
	return HttpResponse("you are loggen in!")

@login_required  ##only logout when u r logged in
def user_logout(request):
	logout(request)

	return HttpResponseRedirect(reverse('index'))




def register(request):

	registered= False

	if request.method == "POST":
		user_form = UserForm(data=request.POST)
		profile_form = userprofileinfoForm(data=request.POST)


		if user_form.is_valid() and profile_form.is_valid():

			user = user_form.save()
			user.set_password(user.password) ##set_password method is for hashing
			user.save()

			profile = profile_form.save(commit=False)

			profile.user  = user  ##defining one to one relationship when we have already declared in the out models.py

			if 'profile_pic' in request.FILES:
				profile.profile_pic = request.FILES['profile_pic']


			profile.save()

			registered = True

		else:
			print(user_form.errors,profile_form.errors)


	else:
		user_form = UserForm()
		profile_form = userprofileinfoForm()

	return render(request,'basic_app/registeration.html',
		{'user_form':user_form,
		  'profile_form':profile_form,
		  'registered':registered})



def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'basic_app/login.html', {})

level_five/templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"> 
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="{% url 'basic_app:registeration' %}">Register<span class="sr-only">(current)</span></a>
      <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>

      {% if user.is_authenticated %}
      <a class = "nav-item nav-link " href="{% url 'logout' %}">Logout</a>

      {% else %}
      <a class="nav-item nav-link active" href="{% url 'basic_app:user_login' %}">Login</a>

      {% endif %}

    </div> 
  </div>
</nav>

<div class="container">
	{% block body_block %}
	{% endblock %} 	
</div>
</body>
</html>

level_five/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
	<h1>Django Level Five</h1>

</div>

{% endblock %}

level_five/templates/basic_app/login.html
{% extends "basic_app/base.html" %}
{% block body_block %}



<div class="jumbotron">
	<h1>Please Login</h1>
	<form action="{% url 'basic_app:user_login' %}" method="POST">
		{% csrf_token %}
		<label for="usename">Username:</label>
		<input type="text" name="username" placeholder="Enter Username">

		<label for="password">Password:</label>
		<input type="password" name="password">

		<input type="submit" name="" value="Login">
	</form>
		
</div>

 

{% endblock %}

level_five/templates/basic_app/registeration.html
{% extends "basic_app/base.html" %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
	{% if registered %}
		<h1>Thankyou for registering!</h1>
	
	{% else %}
	<h1>REgister Here!</h1>
	<h3>Fill out the form</h3>

	<form enctype="multipart/form-data" method="post">
		{% csrf_token %}
		{{ user_form.as_p}}
		{{ profile_form.as_p}}		

		<input type="submit" name="" value="REgister">
	</form>
	{% endif %}	 

</div>
{% endblock %}